const COP_FACTOR = 1000

const rawProducts = [
    // Chaquetas
    {
        id: 1,
        name: "CHAQUETA SOFTSHELL TÁCTICA HUNTER FZ GEN.3",
        originalPrice: 175,
        salePrice: 148.75,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-hunter-olive.webp",
            "/images/products/jacket-hunter-black.webp",
            "/images/products/jacket-hunter-gray.webp",
            "/images/products/jacket-hunter-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "NUEVO",
    },
    {
        id: 2,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ML GEN.3",
        originalPrice: 320,
        salePrice: 272,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-delta-ml-olive.webp",
            "/images/products/jacket-delta-ml-black.webp",
            "/images/products/jacket-delta-ml-gray.webp",
            "/images/products/jacket-delta-ml-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "MÁS VENDIDO",
    },
    {
        id: 3,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ACE PLUS GEN.3",
        originalPrice: 290,
        salePrice: 246.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355", "#2d3e50", "#5a5a5a"],
        images: [
            "/images/products/jacket-ace-olive.webp",
            "/images/products/jacket-ace-black.webp",
            "/images/products/jacket-ace-tan.webp",
            "/images/products/jacket-ace-navy.webp",
            "/images/products/jacket-ace-gray.webp",
        ],
        category: "CHAQUETAS",
        badge: "POPULAR",
    },
    {
        id: 4,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA OL 4.0",
        originalPrice: 399,
        salePrice: 339.15,
        discount: 15,
        colors: ["#4B5320", "#000000", "#2d3e50", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/jacket-ol-olive.webp",
            "/images/products/jacket-ol-black.webp",
            "/images/products/jacket-ol-navy.webp",
            "/images/products/jacket-ol-gray.webp",
            "/images/products/jacket-ol-tan.webp",
        ],
        category: "CHAQUETAS",
        badge: "PREMIUM",
    },
    {
        id: 5,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ACS GEN.3",
        originalPrice: 350,
        salePrice: 297.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-acs-winter-olive.webp",
            "/images/products/jacket-acs-winter-black.webp",
            "/images/products/jacket-acs-winter-gray.webp",
            "/images/products/jacket-acs-winter-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "NUEVO",
    },
    {
        id: 6,
        name: "CHAQUETA SOFTSHELL TÁCTICA DELTA ACS GEN.3",
        originalPrice: 290,
        salePrice: 246.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-acs-soft-olive.webp",
            "/images/products/jacket-acs-soft-black.webp",
            "/images/products/jacket-acs-soft-gray.webp",
            "/images/products/jacket-acs-soft-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "OFERTA",
    },
    {
        id: 7,
        name: "CHAQUETA DE COMBATE STRIKER ULT",
        originalPrice: 270,
        salePrice: 229.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-striker-ult-olive.webp",
            "/images/products/jacket-striker-ult-black.webp",
            "/images/products/jacket-striker-ult-gray.webp",
            "/images/products/jacket-striker-ult-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "LIMITADO",
    },
    {
        id: 8,
        name: "CHAQUETA DE COMBATE STRIKER HT",
        originalPrice: 299,
        salePrice: 254.15,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-striker-ht-olive.webp",
            "/images/products/jacket-striker-ht-black.webp",
            "/images/products/jacket-striker-ht-gray.webp",
            "/images/products/jacket-striker-ht-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "ICONO",
    },
    // Camisas
    {
        id: 14,
        name: "CAMISA DE COMBATE STRIKER XT GEN.3",
        originalPrice: 190,
        salePrice: 161.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/shirt-striker-xt-olive.webp",
            "/images/products/shirt-striker-xt-black.webp",
            "/images/products/shirt-striker-xt-gray.webp",
            "/images/products/shirt-striker-xt-navy.webp",
        ],
        category: "CAMISAS",
        badge: "NUEVO",
    },
    {
        id: 15,
        name: "POLO TÁCTICO URBAN P-40",
        originalPrice: 90,
        salePrice: 76.5,
        discount: 15,
        colors: ["#000000", "#5a5a5a", "#2d3e50", "#8B7355"],
        images: [
            "/images/products/shirt-polo-black.webp",
            "/images/products/shirt-polo-gray.webp",
            "/images/products/shirt-polo-navy.webp",
            "/images/products/shirt-polo-tan.webp",
        ],
        category: "CAMISAS",
        badge: "BESTSELLER",
    },
    {
        id: 16,
        name: "CAMISETA TÁCTICA BLEND",
        originalPrice: 45,
        salePrice: 38.25,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a"],
        images: [
            "/images/products/shirt-blend-olive.webp",
            "/images/products/shirt-blend-black.webp",
            "/images/products/shirt-blend-gray.webp",
        ],
        category: "CAMISAS",
        badge: "OFERTA",
    },
    {
        id: 17,
        name: "CAMISA DE COMBATE ACU",
        originalPrice: 150,
        salePrice: 127.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a"],
        images: [
            "/images/products/shirt-acu-olive.webp",
            "/images/products/shirt-acu-black.webp",
            "/images/products/shirt-acu-gray.webp",
        ],
        category: "CAMISAS",
        badge: "CLÁSICO",
    },
    // Gorras
    {
        id: 18,
        name: "GORRA TÁCTICA LIGERA STRIKER",
        originalPrice: 40,
        salePrice: 34,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50", "#8B7355"],
        images: [
            "/images/products/cap-light-olive.webp",
            "/images/products/cap-light-black.webp",
            "/images/products/cap-light-gray.webp",
            "/images/products/cap-light-navy.webp",
            "/images/products/cap-light-tan.webp",
        ],
        category: "GORRAS",
        badge: "POPULAR",
    },
    {
        id: 19,
        name: "GORRA BASEBALL CON VELCRO",
        originalPrice: 35,
        salePrice: 29.75,
        discount: 15,
        colors: ["#4B5320", "#000000", "#2d3e50"],
        images: [
            "/images/products/cap-baseball-olive.webp",
            "/images/products/cap-baseball-black.webp",
            "/images/products/cap-baseball-navy.webp",
        ],
        category: "GORRAS",
        badge: "BÁSICO",
    },
    {
        id: 20,
        name: "BOONIE HAT GEN.2",
        originalPrice: 55,
        salePrice: 46.75,
        discount: 15,
        colors: ["#4B5320", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/hat-boonie-olive.webp",
            "/images/products/hat-boonie-gray.webp",
            "/images/products/hat-boonie-tan.webp",
        ],
        category: "GORRAS",
        badge: "NECESARIO",
    },
    {
        id: 21,
        name: "GORRA DE INVIERNO WINDBLOCKER",
        originalPrice: 50,
        salePrice: 42.5,
        discount: 15,
        colors: ["#000000", "#5a5a5a"],
        images: [
            "/images/products/cap-winter-black.webp",
            "/images/products/cap-winter-gray.webp",
        ],
        category: "GORRAS",
        badge: "NUEVO",
    },
    // Accesorios
    {
        id: 22,
        name: "CINTURÓN TÁCTICO DUAL D-RING",
        originalPrice: 85,
        salePrice: 72.25,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/belt-dual-olive.webp",
            "/images/products/belt-dual-black.webp",
            "/images/products/belt-dual-gray.webp",
            "/images/products/belt-dual-tan.webp",
        ],
        category: "ACCESORIOS",
        badge: "ESENCIAL",
    },
    {
        id: 23,
        name: "GUANTES DE COMBATE IMPACT",
        originalPrice: 60,
        salePrice: 51,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355"],
        images: [
            "/images/products/gloves-impact-olive.webp",
            "/images/products/gloves-impact-black.webp",
            "/images/products/gloves-impact-tan.webp",
        ],
        category: "ACCESORIOS",
        badge: "POPULAR",
    },
    {
        id: 24,
        name: "RODILLERAS DE COMBATE 3D",
        originalPrice: 45,
        salePrice: 38.25,
        discount: 15,
        colors: ["#000000", "#4B5320"],
        images: [
            "/images/products/knee-pads-black.webp",
            "/images/products/knee-pads-olive.webp",
        ],
        category: "ACCESORIOS",
        badge: "PROTECCIÓN",
    },
    {
        id: 25,
        name: "CODERAS DE COMBATE FLEX",
        originalPrice: 35,
        salePrice: 29.75,
        discount: 15,
        colors: ["#000000", "#4B5320"],
        images: [
            "/images/products/elbow-pads-black.webp",
            "/images/products/elbow-pads-olive.webp",
        ],
        category: "ACCESORIOS",
        badge: "BÁSICO",
    },
    {
        id: 26,
        name: "MOCHILA DE ASALTO 24H",
        originalPrice: 120,
        salePrice: 102,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355", "#5a5a5a"],
        images: [
            "/images/products/backpack-24h-olive.webp",
            "/images/products/backpack-24h-black.webp",
            "/images/products/backpack-24h-tan.webp",
            "/images/products/backpack-24h-gray.webp",
        ],
        category: "ACCESORIOS",
        badge: "NUEVO",
    },
    // Botas
    {
        id: 27,
        name: "Original S.W.A.T. Alpha Fury 2.0 - Botas unisex",
        originalPrice: 595,
        colors: ["#000000"],
        images: [
            "/botas/botas-aa.webp",
            "/botas/botas-a.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 28,
        name: "Original S.W.A.T. Hombres Alpha Fury 2.0 8\" Punta de cuero",
        originalPrice: 595,
        colors: ["#000000"],
        images: [
            "/botas/botas-bbb.webp",
            "/botas/botas-bb.webp",
            "/botas/botas-b.webp",
        ],
        category: "BOTAS",
        badge: "MÁS VENDIDO",
        sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 29,
        name: "NEGRA Altama Botas unisex Vengeance SR",
        originalPrice: 595,
        colors: ["#000000"],
        images: [
            "/botas/botas-c.webp",
            "/botas/botas-cc.webp",
            "/botas/botas-ccc.webp",
        ],
        category: "BOTAS",
        badge: "POPULAR",
        sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 30,
        name: "COYOTE Altama Botas unisex Vengeance SR",
        originalPrice: 595,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-d.webp",
            "/botas/botas-dd.webp",
            "/botas/botas-ddd.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
        sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 32,
        name: "Botas Micro G Stellar Caña Alta con CON CREMALLERA impermeables para HOMBRE",
        originalPrice: 645,
        discount: 10,
        colors: ["#000000", "#8B7355", "#4B5320", "#5a5a5a"],
        images: [
            "/botas/botas-f.webp",
            "/botas/botas-ff.webp",
            "/botas/botas-fff.webp",
            "/botas/botas-ffff.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 33,
        name: "COYOTE Under Armour Caña Baja SIN CREMALLERA Botas Charged Valsetz Mid para hombre",
        originalPrice: 645,
        discount: 10,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-g.webp",
            "/botas/botas-gg.webp",
            "/botas/botas-ggg.webp",
        ],
        category: "BOTAS",
        badge: "ICONO",
        sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 31,
        name: "Under Armour Valsetz RTS - Caña Alta Botas tácticas SIN CREMALLERA para hombre",
        originalPrice: 695,
        discount: 10,
        colors: ["#000000"],
        images: [
            "/botas/botas-e.webp",
            "/botas/botas-ee.webp",
            "/botas/botas-eee.webp",
        ],
        category: "BOTAS",
        badge: "POPULAR",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 34,
        name: "COYOTE Under Armour Caña Baja SIN CREMALLERA Botas Charged Valsetz Mid para hombre",
        originalPrice: 645,
        discount: 10,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-h.webp",
            "/botas/botas-hh.webp",
            "/botas/botas-hhh.webp",
        ],
        category: "BOTAS",
        badge: "MÁS VENDIDO",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 35,
        name: "Coyote Under Armour Valsetz RTS - Caña Alta Botas tácticas SIN CREMALLERA para hombre",
        originalPrice: 695,
        discount: 10,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-iii.webp",
            "/botas/botas-i.webp",
            "/botas/botas-ii.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 36,
        name: "Oakley Botas tácticas Light Patrol para hombre Caña Alta NEGRA",
        originalPrice: 645,
        discount: 10,
        colors: ["#000000"],
        images: [
            "/botas/botas-j.webp",
            "/botas/botas-jj.webp",
            "/botas/botas-jjj.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },

    {
        id: 38,
        name: "LT Assault LTHR by Oakley TODO CUERO",
        originalPrice: 745,
        discount: 10,
        colors: ["#000000"],
        images: [
            "/botas/botas-l.webp",
            "/botas/botas-ll.webp",
            "/botas/botas-lll.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["4", "4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    {
        id: 39,
        name: "Reebok Nano X1 Adventure Tactical CON CREMALLERA para hombre Negra",
        originalPrice: 720,
        discount: 10,
        colors: ["#000000"],
        images: [
            "/botas/botas-mm.webp",
            "/botas/botas-m.webp",
            "/botas/botas-mmm.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 40,
        name: "Reebok Nano X1 Adventure Tactical CON CREMALLERA para hombre COYOTE",
        originalPrice: 739,
        discount: 10,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-nn.webp",
            "/botas/botas-n.webp",
            "/botas/botas-nnn.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 41,
        name: "Reebok Work Trailgrip Tactical 6\" WP Side Zip CON CREMALLERA Botas para hombre COYOTE",
        originalPrice: 739,
        discount: 10,
        colors: ["#8B7355"],
        images: [
            "/botas/botas-o.webp",
            "/botas/botas-oo.webp",
            "/botas/botas-ooo.webp",
        ],
        category: "BOTAS",
        badge: "ÉLITE",
        sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    },
    {
        id: 42,
        name: "Reebok Work Trailgrip Tactical 6\" WP Side Zip CON CREMALLERA Botas para hombre NEGRA",
        originalPrice: 739,
        discount: 10,
        colors: ["#000000"],
        images: [
            "/botas/botas-p.webp",
            "/botas/botas-pp.webp",
            "/botas/botas-ppp.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
        sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14"],
    },
    // Chalecos
    {
        id: 101,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/0ac89852-3d50-49f2-a2fd-f48985d781a7-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 102,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/4f4d2f01-5882-4dde-8be3-f37e3d260ffd-Photoroom-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 103,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/99e7a160-8917-4fd2-ae57-dfb2be68a8b6-Photoroom-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 104,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/9D9A1074-EB0B-40E4-A213-6ABD80A8130A-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 105,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2042-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 106,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2043-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 107,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2044-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 108,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2047-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 109,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2048-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 110,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2049-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 111,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2050-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 112,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_2051-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 113,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_3691-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 114,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_3692-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 115,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_6304-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 116,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/IMG_6716-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 117,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/Photoroom_20260330_144635-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 118,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/f389d4bd-5a33-40de-9a46-eb8050f913ee-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 119,
        name: " ",
        originalPrice: 0,
        salePrice: 0,
        discount: 0,
        colors: ["#000000"],
        images: ["/CHALECOS/f684d3c5-265b-4577-886e-5f3bde5a96a0-Photoroom.JPG"],
        category: "CHALECOS",
        badge: "",
    },
    {
        id: 120,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 1",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/03F0D006-0D05-4A98-A368-0FA73DFA9F53-Photoroom.JPG"]
    },
    {
        id: 121,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 2",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/1030EEAD-4C71-4F3D-9620-577BD9706B7A-Photoroom.JPG"]
    },
    {
        id: 122,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 3",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/292EC2B2-3ACB-4D66-99D0-F369033DCE60-Photoroom.JPG"]
    },
    {
        id: 123,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 4",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/5402E507-AE77-4CA3-B7AD-0852DEF6842E-Photoroom.JPG"]
    },
    {
        id: 124,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 5",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/681C9781-5DF5-4AE5-8C26-7E46C6CFD95F-Photoroom.JPG"]
    },
    {
        id: 125,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 6",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/7EA9D055-272D-46FB-8A25-262837A18960-Photoroom.JPG"]
    },
    {
        id: 126,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 7",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/845B9161-DE2E-4C22-8EDB-659FC923E89C-Photoroom.JPG"]
    },
    {
        id: 127,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 8",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/8C02F7A5-FA95-49F9-8C23-7575CF1F9BF1-Photoroom.JPG"]
    },
    {
        id: 128,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 9",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/A608B093-B847-48D9-BAF4-0A9B30A2E578-Photoroom.JPG"]
    },
    {
        id: 129,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 10",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/A9FF4E27-9FEA-46EF-B54C-18DA45EA844E-Photoroom.JPG"]
    },
    {
        id: 130,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 11",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/D8069200-E201-4058-91EF-4FA1573DAF3F-Photoroom.JPG"]
    },
    {
        id: 131,
        name: "PANTALÓN TÁCTICO ANTIDESGARRO REF. 1.1 - Modelo 12",
        originalPrice: 385,
        salePrice: 365,
        discount: 5,
        specifications: [
            { label: "Referencia", value: "1.1" },
            { label: "Tipo", value: "Pantalón Táctico Antidesgarro" },
            { label: "Material", value: "Tela Ripstop Premium + Elastano (Spandex)" },
            { label: "Costuras", value: "Triple costura reforzada" },
            { label: "Bolsillos", value: "6 bolsillos funcionales" },
            { label: "Tecnología", value: "Antidesgarro • Secado rápido • No requiere plancha" },
            { label: "Uso", value: "Táctico • Militar • Policía • Escoltas • Seguridad • Outdoor" },
            { label: "Garantía", value: "1 año" }
        ],
        colors: ["#8B7355", "#5a5a5a", "#2d3e50", "#000000", "#c2b280", "#4B5320"],
        category: "PANTALONES",
        badge: "NUEVO",
        sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44", "46"],
        description: "Máximo rendimiento. Máxima resistencia. Diseñado para quienes exigen más.\n\nEl Pantalón Táctico Antidesgarro Ref. 1.1 fue desarrollado para operadores tácticos, Fuerzas Militares, Policía, escoltas, seguridad privada y amantes del outdoor que requieren una prenda resistente, cómoda y de alto desempeño.\n\nFabricado con tela Ripstop Premium con elastano (Spandex), ofrece una excelente libertad de movimiento sin sacrificar resistencia, convirtiéndose en uno de los pantalones tácticos más completos del mercado.",
        features: [
            "Tela Ripstop Premium Antidesgarro",
            "Tecnología Antirrasgado",
            "Elastano (Spandex) para mayor comodidad y movilidad",
            "6 bolsillos tácticos funcionales",
            "Triple costura en puntos de mayor esfuerzo e impacto",
            "Secado rápido",
            "No requiere plancha",
            "Alta resistencia al desgaste",
            "Excelente confort para uso prolongado",
            "Conserva su color lavado tras lavado",
            "Diseño ergonómico para máxima movilidad"
        ],
        benefits: [
            "Mayor resistencia en operaciones tácticas.",
            "Libertad total de movimiento gracias a su tejido con elastano.",
            "Ideal para climas cálidos y templados.",
            "Fácil mantenimiento.",
            "Apariencia profesional durante mucho más tiempo.",
            "Diseñado para trabajo, entrenamiento y uso diario."
        ],
        guarantee: "⭐ 1 Año de Garantía\n\nSomos una de las pocas empresas del mercado que respalda este pantalón con 1 año de garantía por defectos de fabricación, reflejando la calidad y confianza de nuestros productos.",
        images: ["/PANTALONES-VEGALTEX/DC20F097-04E6-4C3D-82E3-98AB81E5C077-Photoroom.JPG"]
    }
];

export const products = rawProducts.map((p) => {
    let originalPrice = Math.round(p.originalPrice * COP_FACTOR);
    const discount = p.discount || 0;
    let salePrice = discount > 0
        ? Math.round(originalPrice * (1 - discount / 100))
        : (p.salePrice !== undefined ? Math.round(p.salePrice * COP_FACTOR) : originalPrice);
        
    // Subtract 1 peso so prices end in 999
    if (originalPrice > 0) originalPrice -= 1;
    if (salePrice > 0) salePrice -= 1;
        
    return {
        ...p,
        originalPrice,
        salePrice,
        discount,
    };
})
