const COP_FACTOR = 1000

const rawProducts = [
    // Chaquetas
    {
        id: 1,
        name: "CHAQUETA SOFTSHELL TÁCTICA HUNTER FZ GEN.3",
        originalPrice: 175,
        salePrice: 148.75,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-hunter-olive.webp",
            "/images/products/jacket-hunter-black.webp",
            "/images/products/jacket-hunter-gray.webp",
            "/images/products/jacket-hunter-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "NUEVO",
    },
    {
        id: 2,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ML GEN.3",
        originalPrice: 320,
        salePrice: 272,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-delta-ml-olive.webp",
            "/images/products/jacket-delta-ml-black.webp",
            "/images/products/jacket-delta-ml-gray.webp",
            "/images/products/jacket-delta-ml-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "MÁS VENDIDO",
    },
    {
        id: 3,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ACE PLUS GEN.3",
        originalPrice: 290,
        salePrice: 246.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355", "#2d3e50", "#5a5a5a"],
        images: [
            "/images/products/jacket-ace-olive.webp",
            "/images/products/jacket-ace-black.webp",
            "/images/products/jacket-ace-tan.webp",
            "/images/products/jacket-ace-navy.webp",
            "/images/products/jacket-ace-gray.webp",
        ],
        category: "CHAQUETAS",
        badge: "POPULAR",
    },
    {
        id: 4,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA OL 4.0",
        originalPrice: 399,
        salePrice: 339.15,
        discount: 15,
        colors: ["#4B5320", "#000000", "#2d3e50", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/jacket-ol-olive.webp",
            "/images/products/jacket-ol-black.webp",
            "/images/products/jacket-ol-navy.webp",
            "/images/products/jacket-ol-gray.webp",
            "/images/products/jacket-ol-tan.webp",
        ],
        category: "CHAQUETAS",
        badge: "PREMIUM",
    },
    {
        id: 5,
        name: "CHAQUETA TÁCTICA DE INVIERNO DELTA ACS GEN.3",
        originalPrice: 350,
        salePrice: 297.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-acs-winter-olive.webp",
            "/images/products/jacket-acs-winter-black.webp",
            "/images/products/jacket-acs-winter-gray.webp",
            "/images/products/jacket-acs-winter-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "NUEVO",
    },
    {
        id: 6,
        name: "CHAQUETA SOFTSHELL TÁCTICA DELTA ACS GEN.3",
        originalPrice: 290,
        salePrice: 246.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-acs-soft-olive.webp",
            "/images/products/jacket-acs-soft-black.webp",
            "/images/products/jacket-acs-soft-gray.webp",
            "/images/products/jacket-acs-soft-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "OFERTA",
    },
    {
        id: 7,
        name: "CHAQUETA DE COMBATE STRIKER ULT",
        originalPrice: 270,
        salePrice: 229.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-striker-ult-olive.webp",
            "/images/products/jacket-striker-ult-black.webp",
            "/images/products/jacket-striker-ult-gray.webp",
            "/images/products/jacket-striker-ult-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "LIMITADO",
    },
    {
        id: 8,
        name: "CHAQUETA DE COMBATE STRIKER HT",
        originalPrice: 299,
        salePrice: 254.15,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/jacket-striker-ht-olive.webp",
            "/images/products/jacket-striker-ht-black.webp",
            "/images/products/jacket-striker-ht-gray.webp",
            "/images/products/jacket-striker-ht-navy.webp",
        ],
        category: "CHAQUETAS",
        badge: "ICONO",
    },
    // Pantalones
    {
        id: 9,
        name: "PANTALÓN TÁCTICO STRIKER X GEN.2",
        originalPrice: 240,
        salePrice: 204,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/pants-striker-x-olive.webp",
            "/images/products/pants-striker-x-black.webp",
            "/images/products/pants-striker-x-gray.webp",
            "/images/products/pants-striker-x-navy.webp",
        ],
        category: "PANTALONES",
        badge: "NUEVO",
    },
    {
        id: 10,
        name: "PANTALÓN DE COMBATE STRIKER ULT",
        originalPrice: 260,
        salePrice: 221,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/pants-striker-ult-olive.webp",
            "/images/products/pants-striker-ult-black.webp",
            "/images/products/pants-striker-ult-gray.webp",
            "/images/products/pants-striker-ult-navy.webp",
        ],
        category: "PANTALONES",
        badge: "POPULAR",
    },
    {
        id: 11,
        name: "PANTALÓN TÁCTICO P-40 ALL-TERRAIN GEN.2",
        originalPrice: 180,
        salePrice: 153,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/pants-p40-olive.webp",
            "/images/products/pants-p40-black.webp",
            "/images/products/pants-p40-gray.webp",
            "/images/products/pants-p40-tan.webp",
        ],
        category: "PANTALONES",
        badge: "BESTSELLER",
    },
    {
        id: 12,
        name: "PANTALÓN URBAN TACTICAL P-40",
        originalPrice: 160,
        salePrice: 136,
        discount: 15,
        colors: ["#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/pants-p40-urban-black.webp",
            "/images/products/pants-p40-urban-gray.webp",
            "/images/products/pants-p40-urban-navy.webp",
        ],
        category: "PANTALONES",
        badge: "OFERTA",
    },
    {
        id: 13,
        name: "PANTALÓN DE COMBATE STRIKER HT",
        originalPrice: 220,
        salePrice: 187,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50", "#8B7355"],
        images: [
            "/images/products/pants-striker-ht-olive.webp",
            "/images/products/pants-striker-ht-black.webp",
            "/images/products/pants-striker-ht-gray.webp",
            "/images/products/pants-striker-ht-navy.webp",
            "/images/products/pants-striker-ht-tan.webp",
        ],
        category: "PANTALONES",
        badge: "ICONO",
    },
    // Camisas
    {
        id: 14,
        name: "CAMISA DE COMBATE STRIKER XT GEN.3",
        originalPrice: 190,
        salePrice: 161.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50"],
        images: [
            "/images/products/shirt-striker-xt-olive.webp",
            "/images/products/shirt-striker-xt-black.webp",
            "/images/products/shirt-striker-xt-gray.webp",
            "/images/products/shirt-striker-xt-navy.webp",
        ],
        category: "CAMISAS",
        badge: "NUEVO",
    },
    {
        id: 15,
        name: "POLO TÁCTICO URBAN P-40",
        originalPrice: 90,
        salePrice: 76.5,
        discount: 15,
        colors: ["#000000", "#5a5a5a", "#2d3e50", "#8B7355"],
        images: [
            "/images/products/shirt-polo-black.webp",
            "/images/products/shirt-polo-gray.webp",
            "/images/products/shirt-polo-navy.webp",
            "/images/products/shirt-polo-tan.webp",
        ],
        category: "CAMISAS",
        badge: "BESTSELLER",
    },
    {
        id: 16,
        name: "CAMISETA TÁCTICA BLEND",
        originalPrice: 45,
        salePrice: 38.25,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a"],
        images: [
            "/images/products/shirt-blend-olive.webp",
            "/images/products/shirt-blend-black.webp",
            "/images/products/shirt-blend-gray.webp",
        ],
        category: "CAMISAS",
        badge: "OFERTA",
    },
    {
        id: 17,
        name: "CAMISA DE COMBATE ACU",
        originalPrice: 150,
        salePrice: 127.5,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a"],
        images: [
            "/images/products/shirt-acu-olive.webp",
            "/images/products/shirt-acu-black.webp",
            "/images/products/shirt-acu-gray.webp",
        ],
        category: "CAMISAS",
        badge: "CLÁSICO",
    },
    // Gorras
    {
        id: 18,
        name: "GORRA TÁCTICA LIGERA STRIKER",
        originalPrice: 40,
        salePrice: 34,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#2d3e50", "#8B7355"],
        images: [
            "/images/products/cap-light-olive.webp",
            "/images/products/cap-light-black.webp",
            "/images/products/cap-light-gray.webp",
            "/images/products/cap-light-navy.webp",
            "/images/products/cap-light-tan.webp",
        ],
        category: "GORRAS",
        badge: "POPULAR",
    },
    {
        id: 19,
        name: "GORRA BASEBALL CON VELCRO",
        originalPrice: 35,
        salePrice: 29.75,
        discount: 15,
        colors: ["#4B5320", "#000000", "#2d3e50"],
        images: [
            "/images/products/cap-baseball-olive.webp",
            "/images/products/cap-baseball-black.webp",
            "/images/products/cap-baseball-navy.webp",
        ],
        category: "GORRAS",
        badge: "BÁSICO",
    },
    {
        id: 20,
        name: "BOONIE HAT GEN.2",
        originalPrice: 55,
        salePrice: 46.75,
        discount: 15,
        colors: ["#4B5320", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/hat-boonie-olive.webp",
            "/images/products/hat-boonie-gray.webp",
            "/images/products/hat-boonie-tan.webp",
        ],
        category: "GORRAS",
        badge: "NECESARIO",
    },
    {
        id: 21,
        name: "GORRA DE INVIERNO WINDBLOCKER",
        originalPrice: 50,
        salePrice: 42.5,
        discount: 15,
        colors: ["#000000", "#5a5a5a"],
        images: [
            "/images/products/cap-winter-black.webp",
            "/images/products/cap-winter-gray.webp",
        ],
        category: "GORRAS",
        badge: "NUEVO",
    },
    // Accesorios
    {
        id: 22,
        name: "CINTURÓN TÁCTICO DUAL D-RING",
        originalPrice: 85,
        salePrice: 72.25,
        discount: 15,
        colors: ["#4B5320", "#000000", "#5a5a5a", "#8B7355"],
        images: [
            "/images/products/belt-dual-olive.webp",
            "/images/products/belt-dual-black.webp",
            "/images/products/belt-dual-gray.webp",
            "/images/products/belt-dual-tan.webp",
        ],
        category: "ACCESORIOS",
        badge: "ESENCIAL",
    },
    {
        id: 23,
        name: "GUANTES DE COMBATE IMPACT",
        originalPrice: 60,
        salePrice: 51,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355"],
        images: [
            "/images/products/gloves-impact-olive.webp",
            "/images/products/gloves-impact-black.webp",
            "/images/products/gloves-impact-tan.webp",
        ],
        category: "ACCESORIOS",
        badge: "POPULAR",
    },
    {
        id: 24,
        name: "RODILLERAS DE COMBATE 3D",
        originalPrice: 45,
        salePrice: 38.25,
        discount: 15,
        colors: ["#000000", "#4B5320"],
        images: [
            "/images/products/knee-pads-black.webp",
            "/images/products/knee-pads-olive.webp",
        ],
        category: "ACCESORIOS",
        badge: "PROTECCIÓN",
    },
    {
        id: 25,
        name: "CODERAS DE COMBATE FLEX",
        originalPrice: 35,
        salePrice: 29.75,
        discount: 15,
        colors: ["#000000", "#4B5320"],
        images: [
            "/images/products/elbow-pads-black.webp",
            "/images/products/elbow-pads-olive.webp",
        ],
        category: "ACCESORIOS",
        badge: "BÁSICO",
    },
    {
        id: 26,
        name: "MOCHILA DE ASALTO 24H",
        originalPrice: 120,
        salePrice: 102,
        discount: 15,
        colors: ["#4B5320", "#000000", "#8B7355", "#5a5a5a"],
        images: [
            "/images/products/backpack-24h-olive.webp",
            "/images/products/backpack-24h-black.webp",
            "/images/products/backpack-24h-tan.webp",
            "/images/products/backpack-24h-gray.webp",
        ],
        category: "ACCESORIOS",
        badge: "NUEVO",
    },
    // Botas
    {
        id: 27,
        name: "BOTA TÁCTICA COYOTE STRIKER",
        originalPrice: 195,
        salePrice: 165.75,
        discount: 15,
        colors: ["#8B7355", "#000000"],
        images: [
            "/botas/botas-aa.webp",
            "/botas/botas-a.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
    },
    {
        id: 28,
        name: "BOTA DE COMBATE COMMANDO BLACK",
        originalPrice: 180,
        salePrice: 153,
        discount: 15,
        colors: ["#000000", "#4B5320", "#5a5a5a"],
        images: [
            "/botas/botas-bbb.webp",
            "/botas/botas-bb.webp",
            "/botas/botas-b.webp",
        ],
        category: "BOTAS",
        badge: "MÁS VENDIDO",
    },
    {
        id: 29,
        name: "BOTA IMPERMEABLE DESERT ASSAULT",
        originalPrice: 210,
        salePrice: 178.5,
        discount: 15,
        colors: ["#8B7355", "#000000", "#4B5320"],
        images: [
            "/botas/botas-c.webp",
            "/botas/botas-cc.webp",
            "/botas/botas-ccc.webp",
        ],
        category: "BOTAS",
        badge: "POPULAR",
    },
    {
        id: 30,
        name: "BOTA TÁCTICA MID-CUT LIGHTWEIGHT",
        originalPrice: 165,
        salePrice: 140.25,
        discount: 15,
        colors: ["#5a5a5a", "#000000", "#4B5320"],
        images: [
            "/botas/botas-d.webp",
            "/botas/botas-dd.webp",
            "/botas/botas-ddd.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
    },
    {
        id: 32,
        name: "BOTA TÁCTICA FORCE 10 PLUS",
        originalPrice: 240,
        salePrice: 204,
        discount: 15,
        colors: ["#000000", "#8B7355", "#4B5320", "#5a5a5a"],
        images: [
            "/botas/botas-f.webp",
            "/botas/botas-ff.webp",
            "/botas/botas-fff.webp",
            "/botas/botas-ffff.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
    },
    {
        id: 33,
        name: "BOTA DE CAMPO STRIKER HT",
        originalPrice: 185,
        salePrice: 157.25,
        discount: 15,
        colors: ["#4B5320", "#5a5a5a"],
        images: [
            "/botas/botas-g.webp",
            "/botas/botas-gg.webp",
            "/botas/botas-ggg.webp",
        ],
        category: "BOTAS",
        badge: "ICONO",
    },
    {
        id: 31,
        name: "BOTA RANGER ALL-TERRAIN GEN.2",
        originalPrice: 220,
        salePrice: 187,
        discount: 15,
        colors: ["#8B7355", "#000000", "#5a5a5a"],
        images: [
            "/botas/botas-e.webp",
            "/botas/botas-ee.webp",
            "/botas/botas-eee.webp",
        ],
        category: "BOTAS",
        badge: "POPULAR",
    },
    {
        id: 34,
        name: "BOTA URBAN TACTICAL BLACK OPS",
        originalPrice: 175,
        salePrice: 148.75,
        discount: 15,
        colors: ["#000000", "#5a5a5a"],
        images: [
            "/botas/botas-h.webp",
            "/botas/botas-hh.webp",
            "/botas/botas-hhh.webp",
        ],
        category: "BOTAS",
        badge: "MÁS VENDIDO",
    },
    {
        id: 35,
        name: "BOTA IMPERMEABLE ALPINE TRAIL",
        originalPrice: 255,
        salePrice: 216.75,
        discount: 15,
        colors: ["#8B7355", "#4B5320"],
        images: [
            "/botas/botas-iii.webp",
            "/botas/botas-i.webp",
            "/botas/botas-ii.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
    },
    {
        id: 36,
        name: "BOTA DE COMBATE JUNGLE OPS",
        originalPrice: 200,
        salePrice: 170,
        discount: 15,
        colors: ["#4B5320", "#000000"],
        images: [
            "/botas/botas-j.webp",
            "/botas/botas-jj.webp",
            "/botas/botas-jjj.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
    },
    {
        id: 37,
        name: "BOTA TÁCTICA DESERT STORM",
        originalPrice: 215,
        salePrice: 182.75,
        discount: 15,
        colors: ["#8B7355", "#5a5a5a"],
        images: [
            "/botas/botas-k.webp",
            "/botas/botas-kk.webp",
            "/botas/botas-kkk.webp",
        ],
        category: "BOTAS",
        badge: "POPULAR",
    },
    {
        id: 38,
        name: "BOTA LIGERA SPEEDFORCE",
        originalPrice: 160,
        salePrice: 136,
        discount: 15,
        colors: ["#000000", "#4B5320"],
        images: [
            "/botas/botas-l.webp",
            "/botas/botas-ll.webp",
            "/botas/botas-lll.webp",
        ],
        category: "BOTAS",
        badge: "BÁSICO",
    },
    {
        id: 39,
        name: "BOTA DE MONTAÑA SUMMIT FORCE",
        originalPrice: 270,
        salePrice: 229.5,
        discount: 15,
        colors: ["#5a5a5a", "#8B7355"],
        images: [
            "/botas/botas-mm.webp",
            "/botas/botas-m.webp",
            "/botas/botas-mmm.webp",
        ],
        category: "BOTAS",
        badge: "PREMIUM",
    },
    {
        id: 40,
        name: "BOTA TÁCTICA NIGHTHAWK",
        originalPrice: 230,
        salePrice: 195.5,
        discount: 15,
        colors: ["#000000", "#2d3e50"],
        images: [
            "/botas/botas-nn.webp",
            "/botas/botas-n.webp",
            "/botas/botas-nnn.webp",
        ],
        category: "BOTAS",
        badge: "NUEVO",
    },
    {
        id: 41,
        name: "BOTA DE OPERACIONES ESPECIALES OPS-X",
        originalPrice: 290,
        salePrice: 246.5,
        discount: 15,
        colors: ["#4B5320", "#000000"],
        images: [
            "/botas/botas-o.webp",
            "/botas/botas-oo.webp",
            "/botas/botas-ooo.webp",
        ],
        category: "BOTAS",
        badge: "ÉLITE",
    },
    {
        id: 42,
        name: "BOTA TÁCTICA PATROL CLASSIC",
        originalPrice: 170,
        salePrice: 144.5,
        discount: 15,
        colors: ["#000000", "#8B7355"],
        images: [
            "/botas/botas-p.webp",
            "/botas/botas-pp.webp",
            "/botas/botas-ppp.webp",
        ],
        category: "BOTAS",
        badge: "CLÁSICO",
    }
];

export const products = rawProducts.map((p) => ({
    ...p,
    originalPrice: Math.round(p.originalPrice * COP_FACTOR),
    salePrice: Math.round(p.salePrice * COP_FACTOR),
}))
